title: FPGA Conference Deadlines
description: Countdowns to top FPGA conference deadlines
author: Ruthwik Sunketa

domain: ""
baseurl: ""

github_username: itsruthwik
github_repo: fpga-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
